/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package loadbalancer

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/elbv2"

	svcapitypes "github.com/crossplane/provider-aws/apis/elasticloadbalancingv2/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribeLoadBalancersInput returns input for read
// operation.
func GenerateDescribeLoadBalancersInput(cr *svcapitypes.LoadBalancer) *svcsdk.DescribeLoadBalancersInput {
	res := &svcsdk.DescribeLoadBalancersInput{}

	return res
}

// GenerateLoadBalancer returns the current state in the form of *svcapitypes.LoadBalancer.
func GenerateLoadBalancer(resp *svcsdk.DescribeLoadBalancersOutput) *svcapitypes.LoadBalancer {
	cr := &svcapitypes.LoadBalancer{}

	found := false
	for _, elem := range resp.LoadBalancers {
		if elem.CustomerOwnedIpv4Pool != nil {
			cr.Spec.ForProvider.CustomerOwnedIPv4Pool = elem.CustomerOwnedIpv4Pool
		} else {
			cr.Spec.ForProvider.CustomerOwnedIPv4Pool = nil
		}
		if elem.IpAddressType != nil {
			cr.Spec.ForProvider.IPAddressType = elem.IpAddressType
		} else {
			cr.Spec.ForProvider.IPAddressType = nil
		}
		if elem.Scheme != nil {
			cr.Spec.ForProvider.Scheme = elem.Scheme
		} else {
			cr.Spec.ForProvider.Scheme = nil
		}
		if elem.SecurityGroups != nil {
			f9 := []*string{}
			for _, f9iter := range elem.SecurityGroups {
				var f9elem string
				f9elem = *f9iter
				f9 = append(f9, &f9elem)
			}
			cr.Spec.ForProvider.SecurityGroups = f9
		} else {
			cr.Spec.ForProvider.SecurityGroups = nil
		}
		if elem.Type != nil {
			cr.Spec.ForProvider.Type = elem.Type
		} else {
			cr.Spec.ForProvider.Type = nil
		}
		found = true
		break
	}
	if !found {
		return cr
	}

	return cr
}

// GenerateCreateLoadBalancerInput returns a create input.
func GenerateCreateLoadBalancerInput(cr *svcapitypes.LoadBalancer) *svcsdk.CreateLoadBalancerInput {
	res := &svcsdk.CreateLoadBalancerInput{}

	if cr.Spec.ForProvider.CustomerOwnedIPv4Pool != nil {
		res.SetCustomerOwnedIpv4Pool(*cr.Spec.ForProvider.CustomerOwnedIPv4Pool)
	}
	if cr.Spec.ForProvider.IPAddressType != nil {
		res.SetIpAddressType(*cr.Spec.ForProvider.IPAddressType)
	}
	if cr.Spec.ForProvider.Scheme != nil {
		res.SetScheme(*cr.Spec.ForProvider.Scheme)
	}
	if cr.Spec.ForProvider.SecurityGroups != nil {
		f3 := []*string{}
		for _, f3iter := range cr.Spec.ForProvider.SecurityGroups {
			var f3elem string
			f3elem = *f3iter
			f3 = append(f3, &f3elem)
		}
		res.SetSecurityGroups(f3)
	}
	if cr.Spec.ForProvider.SubnetMappings != nil {
		f4 := []*svcsdk.SubnetMapping{}
		for _, f4iter := range cr.Spec.ForProvider.SubnetMappings {
			f4elem := &svcsdk.SubnetMapping{}
			if f4iter.AllocationID != nil {
				f4elem.SetAllocationId(*f4iter.AllocationID)
			}
			if f4iter.IPv6Address != nil {
				f4elem.SetIPv6Address(*f4iter.IPv6Address)
			}
			if f4iter.PrivateIPv4Address != nil {
				f4elem.SetPrivateIPv4Address(*f4iter.PrivateIPv4Address)
			}
			if f4iter.SubnetID != nil {
				f4elem.SetSubnetId(*f4iter.SubnetID)
			}
			f4 = append(f4, f4elem)
		}
		res.SetSubnetMappings(f4)
	}
	if cr.Spec.ForProvider.Subnets != nil {
		f5 := []*string{}
		for _, f5iter := range cr.Spec.ForProvider.Subnets {
			var f5elem string
			f5elem = *f5iter
			f5 = append(f5, &f5elem)
		}
		res.SetSubnets(f5)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f6 := []*svcsdk.Tag{}
		for _, f6iter := range cr.Spec.ForProvider.Tags {
			f6elem := &svcsdk.Tag{}
			if f6iter.Key != nil {
				f6elem.SetKey(*f6iter.Key)
			}
			if f6iter.Value != nil {
				f6elem.SetValue(*f6iter.Value)
			}
			f6 = append(f6, f6elem)
		}
		res.SetTags(f6)
	}
	if cr.Spec.ForProvider.Type != nil {
		res.SetType(*cr.Spec.ForProvider.Type)
	}

	return res
}

// GenerateDeleteLoadBalancerInput returns a deletion input.
func GenerateDeleteLoadBalancerInput(cr *svcapitypes.LoadBalancer) *svcsdk.DeleteLoadBalancerInput {
	res := &svcsdk.DeleteLoadBalancerInput{}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
